export const SET_MOBIES_DATA = "SET_MOBIES_DATA";
export const SET_LAPTOPS_DATA = "SET_LAPTOPS_DATA";

export const ADD_MOBILE_TO_CART = "ADD_MOBILE_TO_CART";
export const ADD_LAPTOP_TO_CART = "ADD_LAPTOP_TO_CART";

export const REMOVE_ITEMS_IN_CART = "REMOVE_ITEMS_IN_CART";

export const ADD_MORE_ITEMS_COUNT = "ADD_MORE_ITEMS_COUNT";
export const REMOVE_ITEMS_COUNT = "REMOVE_ITEMS_COUNT";